CREATE TABLE `student` (
  `SNO` varchar(50) NOT NULL,
  `SNAME` varchar(50) DEFAULT NULL,
  `SSEX` char(10) DEFAULT NULL,
  PRIMARY KEY (`SNO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO STUDENT VALUES ('001', 'KangKang', 'M');
INSERT INTO STUDENT VALUES ('002', 'Mike', 'M');
INSERT INTO STUDENT VALUES ('003', 'Jane', 'F');